server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:ecom;DB_CLOSE_DELAY=-1;MODE=LEGACY
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,loggers

logging:
  level:
    root: INFO
    org.springframework.security: INFO

jwt:
  issuer: "udacity-ecommerce"
  expiration-minutes: 60
  secret: "temporal-secret"
